"""Template generator for `jailbee config init`.

Writes a fully-populated .jailbee/config.yaml to the target directory. Every
key in the schema appears in the file with its default value, so the file
is self-documenting — users edit values rather than uncomment lines.
"""

from __future__ import annotations

import os
from pathlib import Path

# Repo template is a static string — no per-user values are baked in. Keys
# whose value varies between developers (`container_user.uid/gid`) or
# between checkout locations (`shared_dir`) live in
# ~/.config/jailbee/global.yaml or are auto-derived at load time.
_TEMPLATE = """\
# jailbee configuration. Generated by `jailbee config init`.
# Checked into the repo and shared across the dev team. Anything that
# differs per developer belongs in ~/.config/jailbee/global.yaml instead.
# All keys are optional — delete a key to use the built-in default.
# See docs/config.md for the full reference.

# Container-wide env vars. Injected via the base Incus profile, so they're
# visible in `jailbee shell`, `jailbee tmux`, autostart steps, and any nested shell
# or tmux window. Values are passed through verbatim — no shell expansion.
# Per-step `autostart.env` and step `env` override on collision.
# container:
#   env:
#     NODE_OPTIONS: "--max-old-space-size=4096"
#     EXAMPLE_VAR: "bar"

# Per-repo overrides for credential / IDE / browser blocks. Each block
# defaults to `enabled: false` — opt-in lives in ~/.config/jailbee/global.yaml.
# Override here only when the repo needs to deviate (e.g. force a different
# IDE for this stack, or pin chrome.url to the repo's app URL).
# See docs/config.md for the full schema.
#
# jetbrains:
#   ide: pycharm        # repo's IDE flavour for `jailbee ide` / autostart
# chrome:
#   url: https://app.example.com   # auto-opened URL on `jailbee chrome`

# Repo-specific host bind-mounts (per-project credentials/caches).
# Personal mounts (~/.gnupg, ~/.gitconfig, JetBrains/Toolbox) live in
# ~/.config/jailbee/global.yaml — the lists are appended at load time.
# ~/.ssh is seeded into <shared_dir>/ssh by `jailbee init`, not bind-mounted.
host_mounts: []
# Example:
# host_mounts:
#   - host: ~/.aws
#     container: /home/dev/.aws
#     readonly: true

# Named optional mounts — selectable per-container with `jailbee new --mount NAME`.
optional_mounts: {}
# Example:
# optional_mounts:
#   maven_cache:
#     host: ~/.m2
#     container: /home/dev/.m2
#     description: "Maven local cache"

# Host character/block devices passed into each container as Incus
# unix-char / unix-block devices. Opt-in, default empty.
# jailbee adds the `dev` user to the device's owning group (auto-derived from
# the host node, e.g. /dev/kvm -> kvm) so it can open the node — group
# membership, not `mode`, is what grants access (the container's udev
# resets static_node devices like /dev/kvm to root:kvm 0660 each boot).
# Set `group:` to override the auto-derived group.
# SECURITY: each device widens the host-kernel attack surface reachable
# from inside the (unprivileged) container. /dev/kvm does NOT grant
# container escape on its own, but exposes the KVM kernel subsystem.
# Do not auto-attach; only list devices this repo's workflow needs.
host_devices: []
# Example:
# host_devices:
#   - { path: /dev/kvm }                          # Android emulator / KVM VMs
#   - { source: /dev/bus/usb/001/004, path: /dev/bus/usb/001/004 }

# Host services made reachable inside every container. Each entry becomes an
# Incus proxy device: the container listens on `port`, and connections land on
# `host_port` on the host. Only this direction is configurable — for the
# reverse, use `jailbee port to-host` on one container.
host_ports: []
# host_ports:
#   - { name: adb, port: 5037 }               # host adb server, same port
#   - { name: db, port: 5432, host_port: 15432 }

# Coding agents. Each entry is merged over a shipped preset, so enabling one
# is usually two lines. Every preset field is overridable here — see
# docs/agents.md. Presets: claude, codex, gemini, aider, opencode, grok.
# Only `claude` is exercised in production; the others are untested templates
# — package names, config paths and host lists are best-effort.
#
# When enabled, jailbee for each agent:
#   - bind-mounts its config/auth paths from <shared_dir> so credentials
#     survive container rebuilds and are shared between branches,
#   - adds its hosts to the strict-mode egress allowlist,
#   - installs it at `jailbee new` time (and updates it when auto_update),
#   - launches it in the autostart tmux session when `autostart: true`,
#   - includes its shared dirs in `jailbee doctor` checks.
#
# Commented out on purpose, like the `jetbrains` / `chrome` blocks above:
# repo values win over global ones, so a live `enabled: false` here would
# silently switch off an agent the user opted into in
# ~/.config/jailbee/global.yaml. Opt in globally; override here only when the
# repo needs to deviate.
#
# agents:
#   claude:
#     enabled: true
#     # autostart: false
#     # command: claude
#   codex:
#     enabled: true
#     autostart: true
#
# Legacy: a top-level `claude:` block is still accepted and means the same as
# `agents.claude`. Defining both is an error. Prefer `agents.claude`.

# Egress allowlist applied in strict mode. Each entry is either a literal
# IP/CIDR (e.g. 10.0.0.0/8) or a hostname optionally followed by :PORT
# (e.g. github.com, archive.ubuntu.com:443). Hostnames are resolved to
# IPv4 at ACL-apply time. The `loose` network mode ignores this list
# (everything reachable).
#
# For a one-off host that should not be committed, use
# `jailbee net egress add <host>` instead — it applies to one container (or,
# with --repo, to this host's copy of the repo) and is not shared with the
# team.
egress_allow: []
# Example:
# egress_allow:
#   - github.com
#   - archive.ubuntu.com:443
#   - 10.0.0.0/8

# Golden image config used by `jailbee base build`.
golden:
  # alias defaults to <container_prefix>-base if unset
  ubuntu_version: "26.04"
  java: amazon-corretto-17
  node: 24

# Autostart steps run as the dev user inside the container.
#   on_create: once after `jailbee new` provisions the container (initial setup).
#   on_start:  every stopped→running transition — both `jailbee new` (after
#              on_create) and `jailbee start` (recurring launches, e.g. servers).
# Put one-shot setup in on_create, recurring launches in on_start — don't
# duplicate. IDE and Chrome launch decisions live in `jetbrains.autostart`
# and `chrome.autostart` (not here). See docs/config.md for the full step
# reference.
autostart:
  step_timeout: 600
  # Global env merged into every step (per-step env overrides on collision).
  # env:
  #   SPRING_PROFILES_ACTIVE: dev
  on_create: []
  on_start: []
  # Example:
  # on_create:
  #   - name: setup
  #     run: "make setup"
  #   - name: server
  #     run: "make run"
  #     working_dir: backend
  #     background: true
  #     mounts: [aws]
"""


def render_template(repo_root: Path) -> str:
    """Return the rendered template string.

    `repo_root` is accepted for API compatibility but unused — the repo
    template no longer interpolates per-developer values. UID/GID and
    `shared_dir` either live in `~/.config/jailbee/global.yaml` or are
    auto-derived at config-load time.
    """
    del repo_root  # unused; kept for API compatibility
    return _TEMPLATE


def write_template(repo_root: Path, *, force: bool = False) -> Path:
    """Write .jailbee/config.yaml (or the repo's existing .gie/) under
    repo_root. Returns the written path.

    Raises FileExistsError if the file already exists and force=False.
    """
    from jailbee.paths import repo_config_dir_name

    cfg_dir = repo_root / repo_config_dir_name(repo_root)
    cfg_dir.mkdir(parents=True, exist_ok=True)
    cfg_path = cfg_dir / "config.yaml"

    if cfg_path.exists() and not force:
        raise FileExistsError(f"{cfg_path} already exists. Use --force to overwrite.")

    cfg_path.write_text(render_template(repo_root))
    return cfg_path


_GLOBAL_TEMPLATE = """\
# Per-user jailbee configuration. Generated by `jailbee config init --global`.
# All keys are optional — delete a key to use the built-in default.
# Per-repo `<repo>/.jailbee/config.yaml` overlays this file using deep-merge
# semantics (scalar override, list append, dict merge).
# See docs/config.md for the layered-config reference.

# Container UID/GID. Defaults to current host uid/gid so bind-mounted host
# files (~/.gnupg, ~/.gitconfig) are readable inside the container.
container_user:
  uid: {uid}
  gid: {gid}

# Each integration block below ships with `enabled: false` as its
# built-in default — every host-tooling integration is opt-in. The
# template explicitly flips them on so the file is a working starting
# point; comment out a block (or set `enabled: false`) to disable.

# GPG integration. When enabled, jailbee RO bind-mounts ~/.gnupg into the
# container and sets SSH_AUTH_SOCK to the host gpg-agent's SSH socket so
# YubiKey/GPG-SSH authentication "just works" inside the container.
# Doctor also checks for the gpg-agent socket. Disable if the host has
# no gpg-agent.
gpg:
  enabled: true

# SSH integration. When enabled, jailbee bind-mounts <shared_dir>/ssh as the
# container user's ~/.ssh and enforces 0700 perms on each `jailbee init`.
# `seed_from_host` controls the first-init copy of ~/.ssh/{{config,known_hosts,
# config.d/}}; private keys, authorized_keys and sockets are NEVER seeded.
ssh:
  enabled: true
  seed_from_host: true

# JetBrains integration. `enabled: false` disables `jailbee ide`, suppresses
# autostart launch, and skips the userprefs / toolbox auto-mounts + all
# JetBrains egress entries. When `enabled: true`, strict-mode egress is
# auto-extended with JetBrains' license, plugin marketplace, installer
# CDN and framework hosts so the IDE can activate its license out of
# the box. `ide` selects which JetBrains binary `jailbee ide` (with no
# --app flag) launches; `autostart` controls whether `jailbee new`
# auto-launches that IDE; `userprefs_from_host` (opt-in, off by
# default) RW-binds ~/.java/.userPrefs/jetbrains/ so JetBrains Account
# / license tokens propagate live from host to containers — enable it
# only if you want to reuse the host's JBA login. `share_idea` (default
# true) bind-mounts <shared_dir>/jetbrains-idea over
# ~/<container_prefix>/.idea so project state (run configs, code
# styles, inspection profiles) survives container destruction; set to
# false if the source repo tracks .idea/* files in VCS that should not
# be shadowed. Skipped automatically in --mount mode. `ai_enabled`
# (opt-in, off by default) extends egress with JetBrains AI Assistant
# backends. `toolbox_host_path` RO-mounts JetBrains Toolbox into
# /opt/jetbrains-toolbox; null disables the auto-mount.
# Supported ide: idea | webstorm | pycharm | goland | clion | phpstorm |
#                rider | rubymine | datagrip | rustrover | aqua | dataspell |
#                studio (Android Studio, via JetBrains Toolbox)
jetbrains:
  enabled: true
  ide: idea
  userprefs_from_host: false
  share_idea: true
  ai_enabled: false
  autostart: false
  toolbox_host_path: ~/.local/share/JetBrains/Toolbox

# Chrome integration. `enabled: false` disables `jailbee chrome` and the
# autostart Chrome launch. `url` is the page Chrome opens by default
# (CLI URL arg to `jailbee chrome` overrides it). `dark_mode` forces
# --force-dark-mode regardless of host GTK theme.
# `autostart` controls whether `jailbee new` auto-launches Chrome.
# `host_path` RO-mounts the host Chrome install at /opt/google/chrome
# inside the container; null disables the auto-mount.
chrome:
  enabled: true
  url: null
  dark_mode: false
  autostart: false
  host_path: /opt/google/chrome

# Kitty terminal integration. When `enabled: auto` (default) and the host
# has kitty installed, jailbee RO-binds the host's xterm-kitty terminfo entry
# into every container at /usr/share/terminfo/x/xterm-kitty so curses-aware
# tools (git, less, vim, tmux) don't emit "terminal is not fully functional"
# warnings when `jailbee shell` is launched from a kitty window. `enabled: true`
# fails validation if no terminfo file is found; `enabled: false` disables.
# `host_terminfo_path` overrides the autodetect (which probes
# /usr/share/terminfo/x/xterm-kitty, ~/.local/kitty.app/.../xterm-kitty,
# and ~/.terminfo/x/xterm-kitty in that order).
terminal:
  kitty:
    enabled: auto
    host_terminfo_path: null

# Coding agents. This is the personal, per-developer place to turn one on —
# a repo's own .jailbee/config.yaml can also define `agents:` (and does, for
# team defaults), and the two deep-merge (scalar override, list append). Each
# entry here is itself merged over a shipped preset, so enabling one is
# usually two lines (see `claude:` below, already flipped on as this file's
# working example). Every preset field is overridable — see docs/agents.md.
# Presets: claude, codex, gemini, aider, opencode, grok. Only `claude` is
# exercised in production; the rest are untested templates — package names,
# config paths and host lists are best-effort until someone corrects them.
#
# When an agent is enabled, jailbee, for that agent:
#   - Mounts its config/auth paths from <shared_dir> as bind-mounts inside
#     the container, so credentials and settings survive container rebuilds
#     and are shared between branches. For `claude`: <shared_dir>/claude
#     (RW shared cache) as ~/.claude — credentials, settings, MCP, agents,
#     skills, plugins, and (seeded at <shared_dir>/claude/.claude.json)
#     Claude's identity/onboarding state, read from ~/.claude/.claude.json
#     via CLAUDE_CONFIG_DIR=~/.claude.
#   - Auto-extends strict-mode egress_allow with that agent's hosts — no
#     need to list them by hand below. For `claude`: api.anthropic.com:443,
#     code.claude.com:443, and downloads.claude.ai:443 (CLI self-update).
#     Claude-only: when `plugins_enabled` is true (default), also
#     auto-extends egress_allow with the GitHub + npm hosts Claude Code's
#     plugin marketplace, skills and SessionStart hooks reach; set to false
#     to keep the API reachable while blocking marketplace traffic.
#   - Installs it at `jailbee new` time (and updates it when `auto_update`,
#     the default) and creates its empty shared-dir subpaths on
#     `jailbee init`, checked by `jailbee doctor`. No host dotfiles are
#     read — each agent runs its own onboarding/login flow from a clean
#     state on first launch.
#   - `autostart: true` launches the agent's `command` in the autostart
#     tmux session on every container start; `jailbee tmux <c>` lands
#     directly in that window. Override `command` to pass flags (e.g.
#     "claude --dangerously-skip-permissions").
agents:
  claude:
    enabled: true
    plugins_enabled: true
    # autostart: false
    # command: claude
  # codex:
  #   enabled: true
  #   autostart: true
#
# Legacy: a top-level `claude:` block is still accepted and means the same as
# `agents.claude`. Defining both is an error. Prefer `agents.claude`.

# Shared Claude credential group. Every repo on this host with `agents.claude`
# enabled shares ONE login, stored at
# <XDG_DATA_HOME>/jailbee/claude-credentials/<group>/ and bind-mounted into
# every container as ~/.claude-creds. Only the *credential* is shared: each
# repo keeps its own ~/.claude, so project history, MCP config and sessions
# never cross repos. On a fresh host the first `/login` in any container lands
# in the group directory, and every other repo is logged in from then on.
#
# Host-level only — this key is rejected in a repo's .jailbee/config.yaml,
# because a group name is a property of *this machine's* working set: committed
# to a repo it would apply to every teammate and name a directory that exists
# on one machine only.
#
# `repos:` overrides the group per container_prefix; an explicit `null` keeps
# one repo on its own credential. Edits take effect on the next `jailbee apply`
# in each affected repo, which MOVES that repo's existing credential into the
# group directory — and refuses when both sides already hold one, since one of
# the two logins would become unused and jailbee will not choose for you.
# Set `group: null` to keep every repo on its own login (the behaviour of
# hosts whose global.yaml predates this key). See docs/config.md#claude_credentials.
claude_credentials:
  group: default
  # repos:
  #   my-side-project: personal
  #   experiment: null

# GitHub CLI (gh) integration. When enabled, jailbee:
#   - Auto-extends strict-mode egress_allow with api.github.com:443.
#   - Writes /etc/profile.d/jailbee-github.sh inside the container at
#     autostart, exporting GH_TOKEN for AI agents and login shells.
#   - Runs doctor checks (perms, non-empty, PAT shape).
#
# Tokens are keyed by container_prefix (set in <repo>/.jailbee/config.yaml).
# One entry per GitHub resource owner — fine-grained PATs are scoped to
# one owner each. Recommended: fine-grained PAT (github_pat_*), "Only
# select repositories" + Contents:Read, Issues:RW, Pull requests:RW,
# Metadata:Read. classic PATs (ghp_*) get a doctor warning.
#
# This block is permitted ONLY in this file (~/.config/jailbee/global.yaml).
# Putting it in a repo's .jailbee/config.yaml is rejected at load time so
# tokens cannot leak via git commits. After editing this file, run
# `chmod 600 ~/.config/jailbee/global.yaml`.
github:
  enabled: false
  api_tokens: {{}}
  #   sampleapp: github_pat_AAA...   # one entry per GitHub resource owner
  #   personal:  github_pat_BBB...   # (org or personal account)

# Personal host bind-mount for git credentials. ~/.gnupg, the JetBrains
# Toolbox and the host Chrome install are auto-mounted by the
# gpg/jetbrains/chrome blocks above (manual entries with matching
# container paths win — add one here to override readonly or source).
host_mounts:
  - host: ~/.gitconfig
    container: /home/dev/.gitconfig
    readonly: true

# Extra egress endpoints needed by every repo. Defaults to none — each enabled
# agent in the `agents:` block above appends its own hosts (e.g. `claude` adds
# api.anthropic.com:443 + code.claude.com:443 + downloads.claude.ai:443, plus
# GitHub + npm when plugins_enabled),
# and the jetbrains block auto-adds the JetBrains license / plugin /
# CDN hosts when jetbrains.enabled (plus AI Assistant hosts when
# jetbrains.ai_enabled). Add hostnames here only for endpoints not
# covered by those blocks. Repo-level `egress_allow` appends.
#
# For a one-off host that should not be committed, use
# `jailbee net egress add <host>` instead — it applies to one container (or,
# with --repo, to this host's copy of the repo) and is not shared with the
# team.
egress_allow: []

# Host-level docker registry mirror (host:port). See `jailbee registry up`.
# This block is interpreted with the GlobalConfig schema (host-level),
# NOT the per-repo DockerRegistryMirrorRepoConfig.
# `enabled: auto` (the default) wires the mirror only into repos that ask for
# it: an image that would contain Docker, a repo-level `extra_registries`, or
# `golden.stacks.ecr`. Use `true` to force it on everywhere (it is host-global,
# so that applies to every repo on this machine), `false` to disable.
# docker_registry_mirror:
#   enabled: auto

# Loose-mode auto-revert. When `jailbee net loose <c>` is invoked, the
# container returns to its previous network mode after `after` elapses,
# driven by the existing jailbee-net-refresh.timer. Set `enabled: false` to
# keep the legacy behaviour where loose mode is permanent until manually
# switched. Per-repo .jailbee/config.yaml overrides this file field by
# field — a repo can change just `after` and inherit `enabled` from
# here. Use `jailbee net loose <c> --no-revert` for one-off "stay in loose"
# cases.
loose_auto_revert:
  enabled: true
  after: 5m
"""


def render_global_template() -> str:
    """Return the rendered per-user template string."""
    return _GLOBAL_TEMPLATE.format(uid=os.getuid(), gid=os.getgid())


def write_global_template(*, force: bool = False) -> Path:
    """Write ~/.config/jailbee/global.yaml. Returns the written path.

    Raises FileExistsError if the file already exists and force=False.
    """
    # Local import avoids a circular dependency: global_config imports from
    # config.ConfigError, which lives in the same package as this module.
    from jailbee.global_config import default_global_config_path

    target = default_global_config_path()
    if target.exists() and not force:
        raise FileExistsError(f"{target} already exists. Use --force to overwrite.")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_global_template())
    return target
