"""Template generator for `jailbee config init`.

Writes a fully-populated .jailbee/config.yaml to the target directory. Every
key in the schema appears in the file with its default value, so the file
is self-documenting — users edit values rather than uncomment lines.
"""

from __future__ import annotations

import os
from pathlib import Path

# Repo template is a static string — no per-user values are baked in. Keys
# whose value varies between developers (`container_user.uid/gid`) or
# between checkout locations (`shared_dir`) live in
# ~/.config/jailbee/global.yaml or are auto-derived at load time.
_TEMPLATE = """\
# jailbee configuration. Generated by `jailbee config init`.
# Checked into the repo and shared across the dev team. Anything that
# differs per developer belongs in ~/.config/jailbee/global.yaml instead.
# All keys are optional — delete a key to use the built-in default.
# See docs/config.md for the full reference.

# Container-wide env vars. Injected via the base Incus profile, so they're
# visible in `jailbee shell`, `jailbee tmux`, autostart steps, and any nested shell
# or tmux window. Values are passed through verbatim — no shell expansion.
# Per-step `autostart.env` and step `env` override on collision.
# container:
#   env:
#     NODE_OPTIONS: "--max-old-space-size=4096"
#     EXAMPLE_VAR: "bar"

# Per-repo overrides for credential / IDE / browser blocks. Each block
# defaults to `enabled: false` — opt-in lives in ~/.config/jailbee/global.yaml.
# Override here only when the repo needs to deviate (e.g. force a different
# IDE for this stack, or pin chrome.url to the repo's app URL).
# See docs/config.md for the full schema.
#
# jetbrains:
#   ide: pycharm        # repo's IDE flavour for `jailbee ide` / autostart
# chrome:
#   url: https://app.example.com   # auto-opened URL on `jailbee chrome`

# Repo-specific host bind-mounts (per-project credentials/caches).
# Personal mounts (~/.gnupg, ~/.gitconfig, JetBrains/Toolbox) live in
# ~/.config/jailbee/global.yaml — the lists are appended at load time.
# ~/.ssh is seeded into <shared_dir>/ssh by `jailbee init`, not bind-mounted.
host_mounts: []
# Example:
# host_mounts:
#   - host: ~/.aws
#     container: /home/dev/.aws
#     readonly: true

# Named optional mounts — selectable per-container with `jailbee new --mount NAME`.
optional_mounts: {}
# Example:
# optional_mounts:
#   maven_cache:
#     host: ~/.m2
#     container: /home/dev/.m2
#     description: "Maven local cache"

# Host character/block devices passed into each container as Incus
# unix-char / unix-block devices. Opt-in, default empty.
# jailbee adds the `dev` user to the device's owning group (auto-derived from
# the host node, e.g. /dev/kvm -> kvm) so it can open the node — group
# membership, not `mode`, is what grants access (the container's udev
# resets static_node devices like /dev/kvm to root:kvm 0660 each boot).
# Set `group:` to override the auto-derived group.
# SECURITY: each device widens the host-kernel attack surface reachable
# from inside the (unprivileged) container. /dev/kvm does NOT grant
# container escape on its own, but exposes the KVM kernel subsystem.
# Do not auto-attach; only list devices this repo's workflow needs.
host_devices: []
# Example:
# host_devices:
#   - { path: /dev/kvm }                          # Android emulator / KVM VMs
#   - { source: /dev/bus/usb/001/004, path: /dev/bus/usb/001/004 }

# Host services made reachable inside every container. Each entry becomes an
# Incus proxy device: the container listens on `port`, and connections land on
# `host_port` on the host. Only this direction is configurable — for the
# reverse, use `jailbee port to-host` on one container.
host_ports: []
# host_ports:
#   - { name: adb, port: 5037 }               # host adb server, same port
#   - { name: db, port: 5432, host_port: 15432 }

# Coding agents. Each entry is merged over a shipped preset, so enabling one
# is usually two lines. Every preset field is overridable here — see
# docs/agents.md. Presets: claude, codex, gemini, aider, opencode, grok.
# Only `claude` is exercised in production; the others are untested templates
# — package names, config paths and host lists are best-effort.
#
# When enabled, jailbee for each agent:
#   - bind-mounts its config/auth paths from <shared_dir> so credentials
#     survive container rebuilds and are shared between branches,
#   - adds its hosts to the strict-mode egress allowlist,
#   - installs it at `jailbee new` time (and updates it when auto_update),
#   - launches it in the autostart tmux session when `autostart: true`,
#   - includes its shared dirs in `jailbee doctor` checks.
#
# Commented out on purpose, like the `jetbrains` / `chrome` blocks above:
# repo values win over global ones, so a live `enabled: false` here would
# silently switch off an agent the user opted into in
# ~/.config/jailbee/global.yaml. Opt in globally; override here only when the
# repo needs to deviate.
#
# agents:
#   claude:
#     enabled: true
#     # autostart: false
#     # command: claude
#   codex:
#     enabled: true
#     autostart: true
#
# Legacy: a top-level `claude:` block is still accepted and means the same as
# `agents.claude`. Defining both is an error. Prefer `agents.claude`.

# Egress allowlist applied in strict mode. Each entry is either a literal
# IP/CIDR (e.g. 10.0.0.0/8) or a hostname optionally followed by :PORT
# (e.g. github.com, archive.ubuntu.com:443). Hostnames are resolved to
# IPv4 at ACL-apply time. The `loose` network mode ignores this list
# (everything reachable).
#
# For a one-off host that should not be committed, use
# `jailbee net egress add <host>` instead — it applies to one container (or,
# with --repo, to this host's copy of the repo) and is not shared with the
# team.
egress_allow: []
# Example:
# egress_allow:
#   - github.com
#   - archive.ubuntu.com:443
#   - 10.0.0.0/8

# Golden image config used by `jailbee base build`.
golden:
  # alias defaults to <container_prefix>-base if unset
  ubuntu_version: "26.04"
  java: amazon-corretto-17
  node: 24

# Autostart steps run as the dev user inside the container.
#   on_create: once after `jailbee new` provisions the container (initial setup).
#   on_start:  every stopped→running transition — both `jailbee new` (after
#              on_create) and `jailbee start` (recurring launches, e.g. servers).
# Put one-shot setup in on_create, recurring launches in on_start — don't
# duplicate. IDE and Chrome launch decisions live in `jetbrains.autostart`
# and `chrome.autostart` (not here). See docs/config.md for the full step
# reference.
autostart:
  step_timeout: 600
  # Global env merged into every step (per-step env overrides on collision).
  # env:
  #   SPRING_PROFILES_ACTIVE: dev
  on_create: []
  on_start: []
  # Example:
  # on_create:
  #   - name: setup
  #     run: "make setup"
  #   - name: server
  #     run: "make run"
  #     working_dir: backend
  #     background: true
  #     mounts: [aws]
"""


def render_template(repo_root: Path) -> str:
    """Return the rendered template string.

    `repo_root` is accepted for API compatibility but unused — the repo
    template no longer interpolates per-developer values. UID/GID and
    `shared_dir` either live in `~/.config/jailbee/global.yaml` or are
    auto-derived at config-load time.
    """
    del repo_root  # unused; kept for API compatibility
    return _TEMPLATE


def write_template(repo_root: Path, *, force: bool = False) -> Path:
    """Write .jailbee/config.yaml (or the repo's existing .gie/) under
    repo_root. Returns the written path.

    Raises FileExistsError if the file already exists and force=False.
    """
    from jailbee.paths import repo_config_dir_name

    cfg_dir = repo_root / repo_config_dir_name(repo_root)
    cfg_dir.mkdir(parents=True, exist_ok=True)
    cfg_path = cfg_dir / "config.yaml"

    if cfg_path.exists() and not force:
        raise FileExistsError(f"{cfg_path} already exists. Use --force to overwrite.")

    cfg_path.write_text(render_template(repo_root))
    return cfg_path


GLOBAL_SEED: dict[str, object] = {
    # Defaults to the host uid/gid so bind-mounted host files (~/.gnupg,
    # ~/.gitconfig) stay readable inside the container.
    "container_user": {"uid": os.getuid(), "gid": os.getgid()},
    # Each of these master switches defaults to false in the schema — every
    # host-tooling integration is opt-in. A fresh global config turns the
    # four host-tooling blocks on so the file is a working starting point,
    # matching the hand-written template this replaced. The non-default
    # sub-fields are spelled out explicitly (rather than left to the
    # schema default) so they get their own generated comment.
    "gpg": {"enabled": True},
    "ssh": {"enabled": True, "seed_from_host": True},
    "jetbrains": {
        "enabled": True,
        "ide": "idea",
        "userprefs_from_host": False,
        "share_idea": True,
        "ai_enabled": False,
        "autostart": False,
        "toolbox_host_path": "~/.local/share/JetBrains/Toolbox",
    },
    "chrome": {
        "enabled": True,
        "url": None,
        "dark_mode": False,
        "autostart": False,
        "host_path": "/opt/google/chrome",
    },
    "terminal": {"kitty": {"enabled": "auto", "host_terminfo_path": None}},
    # `agents.claude` is the one exercised in production; enabling it here
    # (rather than leaving `agents` empty) mirrors the old template's
    # working example and keeps Claude Code usable out of the box.
    "agents": {"claude": {"enabled": True, "plugins_enabled": True}},
    # Disabled by default (real behaviour, not just documentation): the
    # file must load cleanly without forcing the user to populate
    # `api_tokens` before first use. Present so the block — and the note
    # that `api_tokens` may only live here, never in a repo config — is
    # documented in every freshly generated file.
    "github": {"enabled": False, "api_tokens": {}},
    "host_mounts": [
        {"host": "~/.gitconfig", "container": "/home/dev/.gitconfig", "readonly": True}
    ],
    "loose_auto_revert": {"enabled": True, "after": "5m"},
}

GLOBAL_SEED_HOST: dict[str, object] = {
    # Host-level key (`config._HOST_LEVEL_KEYS`): modeled on `GlobalConfig`,
    # not `Config`, so it needs its own `render_documented` pass — see
    # `render_global_template`. New hosts share one Claude Code login out
    # of the box; see `docs/config.md#claude_credentials` for why the
    # *schema* default stays `None` while the *generated file* ships
    # `"default"`.
    "claude_credentials": {"group": "default"},
}


def render_global_template() -> str:
    """Return the generated per-user global config.

    Generated rather than templated: each block's comments come from the
    schema's own `description=` fields, so they cannot drift from the code
    the way the previous hand-maintained template did.

    Two `render_documented` passes are concatenated into one file: almost
    every key in `global.yaml` overlays `Config` (gpg, ssh, jetbrains, ...),
    but `claude_credentials` is host-level — read into `GlobalConfig`
    instead, via `_split_host_keys` at load time — so it needs its own pass
    against that model to get a real schema description rather than a raw,
    uncommented value.
    """
    from jailbee.config import Config
    from jailbee.config_writer import DOCUMENTED_HEADER, render_documented
    from jailbee.global_config import GlobalConfig

    config_section = render_documented(GLOBAL_SEED, Config, header=DOCUMENTED_HEADER)
    host_section = render_documented(GLOBAL_SEED_HOST, GlobalConfig, header="")
    return config_section + "\n" + host_section


def write_global_template(*, force: bool = False) -> Path:
    """Write ~/.config/jailbee/global.yaml. Returns the written path.

    Raises FileExistsError if the file already exists and force=False.
    """
    # Local import avoids a circular dependency: global_config imports from
    # config.ConfigError, which lives in the same package as this module.
    from jailbee.global_config import default_global_config_path

    target = default_global_config_path()
    if target.exists() and not force:
        raise FileExistsError(f"{target} already exists. Use --force to overwrite.")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_global_template())
    return target
